# Generated by Django 4.1.7 on 2023-03-14 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('text', models.TextField(max_length=2000, verbose_name='описание')),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.TextField(choices=[('phone', 'телефон'), ('laptop', 'ноутбук')], default='other', verbose_name='категория')),
                ('remainder', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
